#!/system/bin/sh

RISH_APPLICATION_ID="com.termux" \
  /system/bin/app_process -Djava.class.path="/data/data/com.termux/files/usr@rish_shizuku.dex@" \
  /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
