# Copyright (c) 2019-2024, see AUTHORS. Licensed under MIT License, see LICENSE.

{ config, lib, writeText, targetSystem }:

let
  nixCmd = "nix --extra-experimental-features 'flakes nix-command'";
in

writeText "login-inner" ''
  # This file is generated by Nix-on-Droid. DO NOT EDIT.

  # set -eo pipefail

 . "${config.user.home}/.nix-profile/etc/profile.d/nix-on-droid-session-init.sh"

  usershell="${config.user.shell}"
  if [ "$#" -gt 0 ]; then  # if script is not called from within Nix-on-Droid app
    exec /usr/bin/env "$@"
  elif [ -x "$usershell" ]; then
    exec -a "-''${usershell##*/}" "$usershell"
  else
    echo "Cannot execute shell '${config.user.shell}', falling back to bash"
    exec -l bash
  fi
''
